run:
	python script.py docs3 bigramms

run1:
	python script.py karenina1_utf_small bigramms

clean:
	find . -name \*~ -delete
	find . -name \*.backup -delete

	find $(CDIR) -name \*~ -delete
	find $(CDIR) -name \*.backup -delete

